### ISSUE TITLE
vivo兄，你的牙还有救，千万别放弃

### ISSUE THREAD

**Issue by Reopii** [mahavivo/dairy#1]
十年前你在豆瓣的时候我就follow你了，一直跟到微博、推特，还有这里。我也曾受牙病困扰，我想跟你说，你的牙肯定有救，别放弃！十年来我也没有怎么报答过你，才看到你的文字，再不说话，我要自责的。

一、先去大医院

第一步，应该是把主流医学能给你的、「安全」「无副作用」的好处，都利用上。

跟医生说「不拔牙，不做根管治疗」，把所有的治疗方案问到。只要是无副作用的、不会恶化病情的、纯物理的治疗，都可以纳入考虑。一家问不到就去另外一家，医生有义务配合你的要求。搜索「全国口腔医院排名」，去排名上面的医院咨询、做治疗，不要相信小诊所。

当时医生告诉我可以做龈下刮治，也就是彻底清理牙石和牙菌斑，这个是纯物理的。医生跟我反复强调，龈下刮治没啥用我的病情很差只能拔牙……等等。不要听医生说的「必须拔牙」这些话，做龈下刮治一个就够了。

龈下刮治会花费一定时间，但是并不贵，也不痛苦。如果医生给你的方案里面有这个，建议你去做。做了以后可以有效减轻炎症。

二、改变饮食

这一点是和主流医学不一样的。主流医学认为牙病是「卫生」问题，一切问题都可以归结为没好好刷牙；而我要说的这个角度认为，牙病是「营养」问题，牙齿没有得到「正确的、足够的」营养，所以出问题。

建议阅读：

Cure Tooth Decay: Heal and Prevent Cavities with Nutrition ——这本讲了我刚说的「卫生 vs 营养」角度，怎样正确饮食、以及一些针对性的牙齿建议。
Nutrition and Physical Degeneration，作者Weston A. Price —— 这本是历史文献，有台湾翻译《體質大崩壞》。作者游历全球各民族，发现很多原始民族从不刷牙，蛀牙率却很低，一旦接触西方饮食牙齿便急速退化。

这两本书里面讲的饮食，主要就是现在的paleo diet（原始饮食）。可以看：

中文资料：[REDACTED]原始饮食知乎专栏 （从最早的一篇看起）
英文资料：[REDACTED]Paleoleap

我记得你读过营养学教材，paleo diet 和主流营养学的观点是不一样的。我建议：不要光听别人怎么说，自己好好试验。毕竟在第一步里面，医院已经帮你把已有的牙石和牙菌斑去掉了，剩下的完全可以自己验证。

paleo diet的一个缺点是比较费钱，不过也有省钱的办法。

三、额外补救

理论上，饮食对了，牙齿就会好。但是我们这些得牙病的，炎症已经很重了，所以需要额外补救措施：

好好刷牙，用巴氏刷牙法。这点和主流医学观点一样。记得用不含氟的牙膏。如果没有冲牙器，买一个，入门款就可以。记得用低挡，千万不要用高挡。我用waterpik，在4挡以下。

如果牙难受得厉害，可以尝试大剂量维生素C、牛至油。大剂量维生素C指的是每天1g以上，不是药店能买到的那种。我买的是Now Foods 维生素C-1000。维生素C吃多了会腹泻，腹泻意味着已经到了你能承受的上限，但并不像主流观点那样认为有害，可以试试。

可以试试oil pulling，用椰子油，网上有很多教程。还有，牙病常常和心脏有关联，你可以试试补充辅酶Q10。如果要在天然食物里面获得辅酶Q10，主要是动物的心脏。

我还做了一些措施，是按照iherb网上这个评论做的：

how I saved my teeth
Posted by alloriginal on Dec 31, 2012 | Verified Purchase
After neglecting my teeth for over a decade, I finally was forced to a dentists office by a raging infection. The dentist poked and prodded, took xrays and asked how soon I intented to have dentures. With serious gum disease and several cavities, I was right at the tipping point where a future of applesauce and Polident seemed inevitable. I submitted to my first thorough teeth cleaning in decades, and resolved to finally get serious about my teeth and gums. I studied the matter at great length, and came up with a regimen that seems to have worked for me: Each morning I brush with a peroxide-containing toothpaste (Mentadent). I follow this by flossing with dental floss treated with tea tree (Desert Essence, Tea Tree Oil Dental Floss, Waxed, 50 Yds [45.7 m]). I follow this with a mouth rinse using one ounce of hot water, into which I've mixed a teaspoon of colloidal silver (FutureBiotics, Advanced Colloidal Silver, 4 fl oz [118 ml]). I swish the mixture around my mouth for 30 seconds or so, trying to reach between and behind all my teeth. At this point, I've killed as many bad germs as I can. I follow this with one tablespoon of liquid acidophilus (American Health, Probiotic Acidophilus, Plain Flavor, 16 fl oz [472 ml])mixed in one ounce of tepid water. I swish that around for 30 seconds or so, and spit the mixture out. During the day I'll have a couple of xylitol mints (Xlear Inc [Xclear], Spry, Berryblast Mints, Sugar Free, 240 Count, 144 g), which also kills the germs that cause cavities. It leaves my mouth feeling clean. In the evening I repeat the brushing and flossing, but follow it with a different regimen, designed to reduce inflammation and remineralize the teeth: in 2 ounces of warm water I mix a half-teaspoon of colloidal minerals (Trace Minerals Research, ConcenTrace, Trace Mineral Drops, 8 fl oz [237 ml]), a quarter teaspoon of ascorbate (Source Naturals, Ultimate Ascorbate C Powder, 16 oz [453.6 g])and a quarter teaspoon of MSM (Doctor's Best, Best MSM Powder, 250 g). I swish it around for 60 seconds or so, making sure it reaches every corner of my mouth. I believe that this saved my teeth. My dentist noticed that several cavities that he was expecting to fill were no longer there. Moreover, the gum disease that had threatened to have me in dentures was mysteriously cured. I now believe that I'll have my original teeth into my eighties, at least. Thank goodness for Iherb! I believe that nutritional supplements saved my life. I've tried a lot of products, and I know what works and what doesn't. My reviews are honest, straighforward, and based on my experience. Read my other reviews to quickly learn from my three decades of research and experimentation.

简而言之，
刷牙：前面说了
冲牙：我加的是泻盐和海盐，和他的不完全一样
消毒：胶性银（不可长期用）
益生菌：帮助恢复
矿物质、MSM等：帮助牙龈快速得到营养，他也用维C

另外推荐一个网站：[REDACTED]名叫Orawellness。这个网站有一些科普（跟前面的原始饮食一致），也卖产品。我用他家的 HealThy Mouth Blend和牛骨粉。

四、最后的话

医生说，你必须拔牙或者做有风险的手术，因为教材上是这么讲的。教材不一定对啊！教材落后最新研究十几年的事情并不罕见不是？我不能保证我说的这些100%能帮你，但是vivo兄你这么想，我follow你十年了，眼力能差到哪里去？为了我的牙，我没少做功课。

你说：「牙齿接连出问题，对我精神打击较大，这是逐渐步入衰老的明证」——不，这不是你衰老的明证，这不是你的错。我读《體質大崩壞》、读原始饮食专栏，最大的感想就是：我们现代人习以为常的慢性病、体质衰弱、牙齿掉光……并不是人变老必然伴随的。

MC常自豪地说他的文章「领先（中文）世界十年」，vivo兄你也是啊，你不还是十年前那个锋利、生猛的你吗？哪里老了？我现在看不到MC活跃了，不知道他近况，不过我看陆兴华也没老过啊！你只是需要稍稍照顾一下自己的身体，不要受牙病折磨了。

*Edited: Link removed*

**Comment by mahavivo** [comment]
谢谢你这么周到的回复，这么久了我刚看到，抱歉。

我的牙崩坏其实是蛀牙，也有部分牙周炎的因素。其实网上一搜，可以发现很多人20岁左右就满口蛀牙了，拔好几颗。我40岁这样，在中国人牙齿状况里，可能算中等偏下，但远不是最糟糕的。

自从牙齿出了毛病，我也找了一些资料看，一方面是感兴趣，另一方面是实在信不过中国的医生，他们说的话，也仅仅是参考。结合我的实际情况，比较好的治疗方案是戴牙套，防止继续恶化，也消除非常讨厌的塞牙问题，但终究牙齿毛病不大，我又拖延症严重，至今尚未去医院彻底治疗。

开春吧，等天气暖和点，花点时间精力集中解决此一困扰。

再次感谢你的关注和热心建议。

**Comment by Reopii** [comment]
v兄，我这里已经暖和起来啦，给你说声迟到的新年好！

我把Cure Tooth Decay这本书传到百度盘了，省得你费心找

s/1i69MZuX 密码：x3hi

如果还是下不到，libgen上面也有。
